USE [MikroDB_V15_OZPASDEMO];
GO

CREATE NONCLUSTERED INDEX [idx_Nonclustered_CARI_HESAP_HAREKETLERI_cha_tip]
ON [dbo].[CARI_HESAP_HAREKETLERI]
([cha_tip])
INCLUDE ([cha_RECno], [cha_tarihi], [cha_kod])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO
