USE [MikroDB_V15_OZPAS];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE FUNCTION [dbo].[fn_CariHesapAnaDovizBakiye2]
(@FIRMALAR nvarchar(MAX), @CARICINSI tinyint, @CARIKODU nvarchar(25), @SORMERKKODU nvarchar(25), @PROJEKODU nvarchar(25)
, @GRUPNO tinyint, @ILKTARIH datetime, @SONTARIH datetime, @ODEMEEMRIDEGERLEMEDOK tinyint)
RETURNS float
WITH EXEC AS CALLER    -- !!!!!!! :
AS
BEGIN
Declare @Borc as float
Declare @Alacak as float
IF (@ODEMEEMRIDEGERLEMEDOK>0) OR
(@CARICINSI IN (5,9)) OR
(NOT(@ILKTARIH IS NULL)) OR
(NOT(@SONTARIH IS NULL))
BEGIN
Select @Borc   = SUM([msg_S_0101\T] /* ANA DÖVİZ BORÇ */ ),
@Alacak = SUM([msg_S_0102\T] /* ANA DÖVİZ ALACAK */ )
FROM dbo.fn_CariTutarlar (@FIRMALAR, @CARICINSI, @CARIKODU, @GRUPNO, @ILKTARIH, @SONTARIH , @ODEMEEMRIDEGERLEMEDOK , @SORMERKKODU, @PROJEKODU)
END
ELSE SET @Borc = dbo.fn_CariHesapBakiye(@FIRMALAR , @CARICINSI , @CARIKODU , @SORMERKKODU , @PROJEKODU , @GRUPNO , 0 )
RETURN ISNULL(@Borc,0) - ISNULL(@Alacak,0)
END
GO